- name: Deploy website
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Sync local build dir with bucket
      s3_sync:
        bucket: alancovarrubias
        file_root: ../build
        permission: public-read
        region: us-east-2
